# Generated by Django 4.2 on 2023-05-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_customer_deliveryman_stock_supplier_order_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='stockapp.product'),
        ),
    ]
