# Generated by Django 4.2 on 2023-05-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='product',
        ),
        migrations.AddField(
            model_name='facture',
            name='product',
            field=models.ManyToManyField(to='stockapp.product'),
        ),
    ]
