# Generated by Django 4.2 on 2023-05-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_remove_facture_product_facture_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
